from __future__ import annotations

from typing import Dict, Optional

import torch
import torch.nn as nn
import torch.nn.functional as F


def _as_column(x: torch.Tensor) -> torch.Tensor:
    if x.ndim == 1:
        return x.unsqueeze(1)
    if x.ndim > 2:
        return x.reshape(x.shape[0], -1)[:, :1]
    return x


def _expand_mask(mask: torch.Tensor, values: torch.Tensor) -> torch.Tensor:
    mask = mask.to(device=values.device, dtype=values.dtype)
    while mask.ndim < values.ndim:
        mask = mask.unsqueeze(-1)
    return mask


def _masked_mean(values: torch.Tensor, mask: torch.Tensor, eps: float) -> torch.Tensor:
    mask = _expand_mask(mask, values)
    return (values * mask).sum() / mask.sum().clamp_min(eps)


def _masked_smooth_l1(
    pred: torch.Tensor,
    target: torch.Tensor,
    mask: torch.Tensor,
    beta: float,
    eps: float,
) -> torch.Tensor:
    raw = F.smooth_l1_loss(
        pred,
        target,
        beta=max(float(beta), eps),
        reduction="none",
    )
    return _masked_mean(raw, mask, eps)


def masked_softargmin_value(
    values: torch.Tensor,
    mask: torch.Tensor,
    tau: float,
    eps: float = 1e-6,
) -> torch.Tensor:
    """Differentiable min proxy without the log(N) bias of normalized logsumexp.

    Args:
        values: B x K tensor.
        mask: B x K boolean or numeric mask.
        tau: softmin temperature.

    Returns:
        B x 1 differentiable soft-min value.
    """
    tau = max(float(tau), eps)
    valid = mask.bool() & torch.isfinite(values)

    logits = -values / tau
    logits = torch.where(valid, logits, torch.full_like(logits, -1e9))

    weights = torch.softmax(logits, dim=1)
    weights = torch.where(valid, weights, torch.zeros_like(weights))
    weights = weights / weights.sum(dim=1, keepdim=True).clamp_min(eps)

    cleaned = torch.where(valid, values, torch.zeros_like(values))
    return torch.sum(weights * cleaned, dim=1, keepdim=True)


class PhysicsArmCBFLoss(nn.Module):
    """Link-aware physics loss for SafeLIBERO CBF datasets.

    Dataset interpretation:
    - h_star_robust is the EE signed clearance generated by the selected
      safety_distance_mode. In the current dataset, this is knn_capped.
    - h_star_hard is the nearest-point conservative EE clearance.
    - d_gt_keypoints and d_gt_links are whole-arm clearances computed from
      observed obstacle pointclouds and robot keypoint/link capsules.
    - EE regression and EE classification mainly use h_star_robust because the
      current dataset was balanced on h_star = h_star_robust.
    - h_star_hard is retained as conservative auxiliary supervision.
    - Arm supervision uses d_gt_links because no robust arm target is currently
      stored in the dataset.
    """

    def __init__(
        self,
        lambda_ee: float = 1.0,
        lambda_link: float = 1.0,
        lambda_kp: float = 0.5,
        lambda_min: float = 1.0,
        lambda_cls: float = 0.2,
        lambda_rep: float = 0.0,
        lambda_cons: float = 0.3,
        lambda_false_safe: float = 0.0,
        lambda_eik: float = 0.0,
        lambda_rank: float = 0.0,
        ee_hard_weight: float = 0.3,
        ee_robust_weight: float = 1.0,
        false_safe_ee_weight: float = 1.0,
        false_safe_arm_weight: float = 1.0,
        smooth_l1_beta: float = 0.02,
        softmin_tau: float = 0.02,
        cls_beta: float = 25.0,
        conservative_sigma: float = 0.05,
        eik_boundary_band: float = 0.04,
        eik_target_norm: float = 1.0,
        rank_margin: float = 0.005,
        rank_min_gap: float = 0.01,
        eps: float = 1e-6,
    ) -> None:
        super().__init__()

        self.lambda_ee = float(lambda_ee)
        self.lambda_link = float(lambda_link)
        self.lambda_kp = float(lambda_kp)
        self.lambda_min = float(lambda_min)
        self.lambda_cls = float(lambda_cls)
        self.lambda_rep = float(lambda_rep)
        self.lambda_cons = float(lambda_cons)
        self.lambda_false_safe = float(lambda_false_safe)
        self.lambda_eik = float(lambda_eik)
        self.lambda_rank = float(lambda_rank)

        self.ee_hard_weight = float(ee_hard_weight)
        self.ee_robust_weight = float(ee_robust_weight)

        self.false_safe_ee_weight = float(false_safe_ee_weight)
        self.false_safe_arm_weight = float(false_safe_arm_weight)

        self.smooth_l1_beta = float(smooth_l1_beta)
        self.softmin_tau = float(softmin_tau)
        self.cls_beta = float(cls_beta)
        self.conservative_sigma = float(conservative_sigma)
        self.eik_boundary_band = float(eik_boundary_band)
        self.eik_target_norm = float(eik_target_norm)
        self.rank_margin = float(rank_margin)
        self.rank_min_gap = float(rank_min_gap)
        self.eps = float(eps)

    def _target_arm_terms(
        self,
        d_gt_links: torch.Tensor,
        link_mask: torch.Tensor,
        safety_margin: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        d_arm_gt = masked_softargmin_value(
            d_gt_links,
            mask=link_mask,
            tau=self.softmin_tau,
            eps=self.eps,
        )
        h_arm_gt = d_arm_gt - safety_margin
        return d_arm_gt, h_arm_gt

    def _ranking_loss(
        self,
        h_pred: torch.Tensor,
        h_target: torch.Tensor,
    ) -> torch.Tensor:
        if h_pred.shape[0] < 2:
            return h_pred.new_tensor(0.0)

        target_flat = h_target.reshape(-1).detach()
        pred_flat = h_pred.reshape(-1)

        order = torch.argsort(target_flat)
        low_idx = order[:-1]
        high_idx = order[1:]

        target_gap = target_flat[high_idx] - target_flat[low_idx]
        valid = target_gap > self.rank_min_gap
        if not torch.any(valid):
            return h_pred.new_tensor(0.0)

        raw = F.relu(self.rank_margin + pred_flat[low_idx] - pred_flat[high_idx])
        return raw[valid].mean()

    def forward(
        self,
        *,
        h_ee_pred: torch.Tensor,
        d_keypoints_pred: torch.Tensor,
        d_links_pred: torch.Tensor,
        h_total_pred: torch.Tensor,
        d_arm_pred: torch.Tensor,
        h_arm_pred: torch.Tensor,
        v_rep_pred: torch.Tensor,
        h_star_hard: torch.Tensor,
        h_star_robust: torch.Tensor,
        d_gt_keypoints: torch.Tensor,
        d_gt_links: torch.Tensor,
        robot_keypoint_valid_mask: torch.Tensor,
        robot_link_valid_mask: torch.Tensor,
        safety_margin: torch.Tensor,
        v_rep: torch.Tensor,
        v_rep_knn: Optional[torch.Tensor] = None,
        grad_q: Optional[torch.Tensor] = None,
    ) -> Dict[str, torch.Tensor]:
        # ------------------------------------------------------------------
        # Shape / dtype normalization
        # ------------------------------------------------------------------
        h_ee_pred = _as_column(h_ee_pred)
        h_total_pred = _as_column(h_total_pred)
        d_arm_pred = _as_column(d_arm_pred)
        h_arm_pred = _as_column(h_arm_pred)

        h_star_hard = _as_column(h_star_hard).to(
            device=h_ee_pred.device,
            dtype=h_ee_pred.dtype,
        )
        h_star_robust = _as_column(h_star_robust).to(
            device=h_ee_pred.device,
            dtype=h_ee_pred.dtype,
        )
        safety_margin = _as_column(safety_margin).to(
            device=h_ee_pred.device,
            dtype=h_ee_pred.dtype,
        )

        d_gt_keypoints = d_gt_keypoints.to(
            device=h_ee_pred.device,
            dtype=h_ee_pred.dtype,
        )
        d_gt_links = d_gt_links.to(
            device=h_ee_pred.device,
            dtype=h_ee_pred.dtype,
        )

        kp_mask = robot_keypoint_valid_mask.to(device=h_ee_pred.device).bool()
        link_mask = robot_link_valid_mask.to(device=h_ee_pred.device).bool()

        kp_mask = kp_mask & torch.isfinite(d_gt_keypoints)
        link_mask = link_mask & torch.isfinite(d_gt_links)

        d_gt_keypoints_clean = torch.nan_to_num(
            d_gt_keypoints,
            nan=0.0,
            posinf=0.0,
            neginf=0.0,
        )
        d_gt_links_clean = torch.nan_to_num(
            d_gt_links,
            nan=0.0,
            posinf=0.0,
            neginf=0.0,
        )

        # ------------------------------------------------------------------
        # EE regression
        # Main target: robust.
        # Auxiliary conservative target: hard.
        # ------------------------------------------------------------------
        l_ee_hard = F.smooth_l1_loss(
            h_ee_pred,
            h_star_hard,
            beta=max(self.smooth_l1_beta, self.eps),
            reduction="mean",
        )
        l_ee_robust = F.smooth_l1_loss(
            h_ee_pred,
            h_star_robust,
            beta=max(self.smooth_l1_beta, self.eps),
            reduction="mean",
        )
        l_ee = self.ee_hard_weight * l_ee_hard + self.ee_robust_weight * l_ee_robust

        # ------------------------------------------------------------------
        # Link/keypoint regression
        # ------------------------------------------------------------------
        l_kp = _masked_smooth_l1(
            d_keypoints_pred,
            d_gt_keypoints_clean,
            kp_mask,
            beta=self.smooth_l1_beta,
            eps=self.eps,
        )

        l_link = _masked_smooth_l1(
            d_links_pred,
            d_gt_links_clean,
            link_mask,
            beta=self.smooth_l1_beta,
            eps=self.eps,
        )

        # ------------------------------------------------------------------
        # Arm target and total h target
        # ------------------------------------------------------------------
        d_arm_gt, h_arm_gt = self._target_arm_terms(
            d_gt_links_clean,
            link_mask,
            safety_margin=safety_margin,
        )

        h_total_gt = masked_softargmin_value(
            torch.cat([h_star_robust, h_arm_gt], dim=1),
            mask=torch.ones(
                (h_star_robust.shape[0], 2),
                device=h_star_robust.device,
                dtype=torch.bool,
            ),
            tau=self.softmin_tau,
            eps=self.eps,
        )

        l_min = F.smooth_l1_loss(
            d_arm_pred,
            d_arm_gt,
            beta=max(self.smooth_l1_beta, self.eps),
            reduction="mean",
        )

        # ------------------------------------------------------------------
        # Classification loss
        # EE classification uses robust target.
        # Arm classification uses arm hard-min target.
        # ------------------------------------------------------------------
        unsafe_ee = (h_star_robust < 0.0).to(dtype=h_ee_pred.dtype)
        unsafe_arm = (h_arm_gt < 0.0).to(dtype=h_ee_pred.dtype)

        l_cls_ee = F.binary_cross_entropy_with_logits(
            -self.cls_beta * h_ee_pred,
            unsafe_ee,
        )
        l_cls_arm = F.binary_cross_entropy_with_logits(
            -self.cls_beta * h_arm_pred,
            unsafe_arm,
        )
        l_cls = 0.5 * (l_cls_ee + l_cls_arm)

        # ------------------------------------------------------------------
        # False-safe asymmetric loss
        # Penalizes only dangerous optimism:
        # target unsafe, prediction safe.
        #
        # For EE:  h_star_robust < 0 and h_ee_pred > 0.
        # For arm: h_arm_gt < 0 and h_arm_pred > 0.
        # ------------------------------------------------------------------
        unsafe_ee_mask = (h_star_robust < 0.0).to(dtype=h_ee_pred.dtype)
        unsafe_arm_mask = (h_arm_gt < 0.0).to(dtype=h_ee_pred.dtype)

        l_false_safe_ee = (
            unsafe_ee_mask * F.relu(h_ee_pred).pow(2)
        ).sum() / unsafe_ee_mask.sum().clamp_min(1.0)

        l_false_safe_arm = (
            unsafe_arm_mask * F.relu(h_arm_pred).pow(2)
        ).sum() / unsafe_arm_mask.sum().clamp_min(1.0)

        denom_fs = max(
            self.false_safe_ee_weight + self.false_safe_arm_weight,
            self.eps,
        )
        l_false_safe = (
            self.false_safe_ee_weight * l_false_safe_ee
            + self.false_safe_arm_weight * l_false_safe_arm
        ) / denom_fs

        # ------------------------------------------------------------------
        # Repulsive direction auxiliary loss
        # Usually lambda_rep=0.0 for current main runs.
        # ------------------------------------------------------------------
        rep_target = v_rep_knn if v_rep_knn is not None else v_rep
        rep_target = rep_target.to(device=h_ee_pred.device, dtype=h_ee_pred.dtype)

        rep_pred_norm = torch.linalg.norm(
            v_rep_pred,
            dim=-1,
            keepdim=True,
        ).clamp_min(self.eps)
        rep_tgt_norm = torch.linalg.norm(
            rep_target,
            dim=-1,
            keepdim=True,
        ).clamp_min(self.eps)

        rep_cos = (
            (v_rep_pred / rep_pred_norm) * (rep_target / rep_tgt_norm)
        ).sum(dim=-1, keepdim=True).clamp(-1.0, 1.0)

        rep_valid = (rep_tgt_norm > 1e-4).to(dtype=h_ee_pred.dtype)
        l_rep = _masked_mean(1.0 - rep_cos, rep_valid, self.eps)

        # ------------------------------------------------------------------
        # Conservative loss
        # Penalizes optimistic predictions near hard boundaries.
        # ------------------------------------------------------------------
        cons_weight_ee = torch.exp(
            -h_star_hard.abs() / max(self.conservative_sigma, self.eps)
        )
        l_cons_ee = torch.mean(
            cons_weight_ee * F.relu(h_ee_pred - h_star_hard).pow(2)
        )

        link_boundary = d_gt_links_clean - safety_margin
        cons_weight_link = torch.exp(
            -link_boundary.abs() / max(self.conservative_sigma, self.eps)
        )
        cons_link_raw = cons_weight_link * F.relu(d_links_pred - d_gt_links_clean).pow(2)
        l_cons_link = _masked_mean(cons_link_raw, link_mask, self.eps)

        l_cons = 0.5 * (l_cons_ee + l_cons_link)

        # ------------------------------------------------------------------
        # Eikonal loss
        # Keep lambda_eik=0.0 unless q -> FK -> keypoints is differentiable.
        # ------------------------------------------------------------------
        l_eik = h_ee_pred.new_tensor(0.0)
        grad_norm = h_ee_pred.new_zeros((h_ee_pred.shape[0], 1))

        if grad_q is not None:
            grad_norm = torch.linalg.norm(
                grad_q,
                dim=-1,
                keepdim=True,
            ).clamp_min(self.eps)

            boundary = (h_total_gt.abs() < self.eik_boundary_band).to(
                dtype=h_ee_pred.dtype
            )

            l_eik = _masked_mean(
                (grad_norm - self.eik_target_norm).pow(2),
                boundary,
                self.eps,
            )

        # ------------------------------------------------------------------
        # Ranking loss
        # ------------------------------------------------------------------
        l_rank = self._ranking_loss(h_total_pred, h_total_gt)

        # ------------------------------------------------------------------
        # Total loss
        # ------------------------------------------------------------------
        loss = (
            self.lambda_ee * l_ee
            + self.lambda_link * l_link
            + self.lambda_kp * l_kp
            + self.lambda_min * l_min
            + self.lambda_cls * l_cls
            + self.lambda_rep * l_rep
            + self.lambda_cons * l_cons
            + self.lambda_false_safe * l_false_safe
            + self.lambda_eik * l_eik
            + self.lambda_rank * l_rank
        )

        # ------------------------------------------------------------------
        # Metrics
        # ------------------------------------------------------------------
        with torch.no_grad():
            # EE robust metrics.
            unsafe_ee_bool = h_star_robust < 0.0
            safe_ee_bool = h_star_robust >= 0.0
            pred_unsafe_ee_bool = h_ee_pred < 0.0
            pred_safe_ee_bool = h_ee_pred >= 0.0

            # EE hard metrics.
            unsafe_ee_hard_bool = h_star_hard < 0.0
            safe_ee_hard_bool = h_star_hard >= 0.0

            # Arm metrics.
            unsafe_arm_bool = h_arm_gt < 0.0
            safe_arm_bool = h_arm_gt >= 0.0
            pred_unsafe_arm_bool = h_arm_pred < 0.0
            pred_safe_arm_bool = h_arm_pred >= 0.0

            ee_sign_acc = (
                pred_unsafe_ee_bool == unsafe_ee_bool
            ).to(dtype=h_ee_pred.dtype).mean()

            arm_sign_acc = (
                pred_unsafe_arm_bool == unsafe_arm_bool
            ).to(dtype=h_ee_pred.dtype).mean()

            ee_hard_sign_acc = (
                pred_unsafe_ee_bool == unsafe_ee_hard_bool
            ).to(dtype=h_ee_pred.dtype).mean()

            ee_robust_sign_acc = (
                pred_unsafe_ee_bool == unsafe_ee_bool
            ).to(dtype=h_ee_pred.dtype).mean()

            false_safe_ee_rate = (
                (pred_safe_ee_bool & unsafe_ee_bool).to(dtype=h_ee_pred.dtype).sum()
                / unsafe_ee_bool.to(dtype=h_ee_pred.dtype).sum().clamp_min(1.0)
            )

            false_safe_arm_rate = (
                (pred_safe_arm_bool & unsafe_arm_bool).to(dtype=h_ee_pred.dtype).sum()
                / unsafe_arm_bool.to(dtype=h_ee_pred.dtype).sum().clamp_min(1.0)
            )

            false_unsafe_ee_rate = (
                (pred_unsafe_ee_bool & safe_ee_bool).to(dtype=h_ee_pred.dtype).sum()
                / safe_ee_bool.to(dtype=h_ee_pred.dtype).sum().clamp_min(1.0)
            )

            false_unsafe_arm_rate = (
                (pred_unsafe_arm_bool & safe_arm_bool).to(dtype=h_ee_pred.dtype).sum()
                / safe_arm_bool.to(dtype=h_ee_pred.dtype).sum().clamp_min(1.0)
            )

            false_safe_ee_hard_rate = (
                (pred_safe_ee_bool & unsafe_ee_hard_bool).to(dtype=h_ee_pred.dtype).sum()
                / unsafe_ee_hard_bool.to(dtype=h_ee_pred.dtype).sum().clamp_min(1.0)
            )

            false_unsafe_ee_hard_rate = (
                (pred_unsafe_ee_bool & safe_ee_hard_bool).to(dtype=h_ee_pred.dtype).sum()
                / safe_ee_hard_bool.to(dtype=h_ee_pred.dtype).sum().clamp_min(1.0)
            )

            link_valid_fraction = link_mask.to(dtype=h_ee_pred.dtype).mean()
            kp_valid_fraction = kp_mask.to(dtype=h_ee_pred.dtype).mean()

        return {
            "loss": loss,

            "L_ee": l_ee.detach(),
            "L_ee_hard": l_ee_hard.detach(),
            "L_ee_robust": l_ee_robust.detach(),

            "L_kp": l_kp.detach(),
            "L_link": l_link.detach(),
            "L_min": l_min.detach(),

            "L_cls": l_cls.detach(),
            "L_cls_ee": l_cls_ee.detach(),
            "L_cls_arm": l_cls_arm.detach(),

            "L_false_safe": l_false_safe.detach(),
            "L_false_safe_ee": l_false_safe_ee.detach(),
            "L_false_safe_arm": l_false_safe_arm.detach(),

            "L_rep": l_rep.detach(),

            "L_cons": l_cons.detach(),
            "L_cons_ee": l_cons_ee.detach(),
            "L_cons_link": l_cons_link.detach(),

            "L_eik": l_eik.detach(),
            "L_rank": l_rank.detach(),

            "mean_h_ee_pred": h_ee_pred.detach().mean(),
            "mean_h_ee_gt": h_star_robust.detach().mean(),
            "mean_h_ee_hard_gt": h_star_hard.detach().mean(),
            "mean_h_ee_robust_gt": h_star_robust.detach().mean(),

            "mean_d_arm_pred": d_arm_pred.detach().mean(),
            "mean_d_arm_gt": d_arm_gt.detach().mean(),
            "mean_h_arm_pred": h_arm_pred.detach().mean(),
            "mean_h_arm_gt": h_arm_gt.detach().mean(),

            "mean_h_total_pred": h_total_pred.detach().mean(),
            "mean_h_total_gt": h_total_gt.detach().mean(),

            "mean_grad_q_norm": grad_norm.detach().mean(),

            "rep_cos": _masked_mean(rep_cos.detach(), rep_valid, self.eps),

            "ee_sign_acc": ee_sign_acc.detach(),
            "arm_sign_acc": arm_sign_acc.detach(),
            "ee_hard_sign_acc": ee_hard_sign_acc.detach(),
            "ee_robust_sign_acc": ee_robust_sign_acc.detach(),

            "false_safe_ee_rate": false_safe_ee_rate.detach(),
            "false_safe_arm_rate": false_safe_arm_rate.detach(),
            "false_unsafe_ee_rate": false_unsafe_ee_rate.detach(),
            "false_unsafe_arm_rate": false_unsafe_arm_rate.detach(),

            "false_safe_ee_hard_rate": false_safe_ee_hard_rate.detach(),
            "false_unsafe_ee_hard_rate": false_unsafe_ee_hard_rate.detach(),

            "link_valid_fraction": link_valid_fraction.detach(),
            "kp_valid_fraction": kp_valid_fraction.detach(),
        }


Loss = PhysicsArmCBFLoss