benchmark_root: /home/olaf/Claudio/vlsa-aegis/safelibero/safelibero/libero/libero
bddl_files: /home/olaf/Claudio/vlsa-aegis/safelibero/safelibero/libero/libero/bddl_files
init_states: /home/olaf/Claudio/vlsa-aegis/safelibero/safelibero/libero/libero/init_files
datasets: /home/olaf/Claudio/vlsa-aegis/safelibero/safelibero/libero/datasets
assets: /home/olaf/Claudio/vlsa-aegis/safelibero/safelibero/libero/libero/assets
